global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:8093']
    metrics_path: '/actuator/prometheus'

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']



