{
 "title": "Events consumed",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total consumed events",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_grifols_dig_software_instrument_domain_event_InstrumentTaskWasCreatedEvent_total{TAG_KEY_EVENT_DISPATCHING=\"EVENT_STORE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_grifols_dig_software_instrument_domain_event_OperationWasCreatedEvent_total{TAG_KEY_EVENT_DISPATCHING=\"EVENT_STORE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_grifols_dig_software_order_domain_event_OrderTaskWasCreatedEvent_total{TAG_KEY_EVENT_DISPATCHING=\"EVENT_STORE\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$A +$B + $C", "type": "math" }
   ]
  },
  {
   "title": "InstrumentTaskWasCreatedEvent consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_grifols_dig_software_instrument_domain_event_InstrumentTaskWasCreatedEvent_total{TAG_KEY_EVENT_DISPATCHING=\"EVENT_STORE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OperationWasCreatedEvent consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_grifols_dig_software_instrument_domain_event_OperationWasCreatedEvent_total{TAG_KEY_EVENT_DISPATCHING=\"EVENT_STORE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OrderTaskWasCreatedEvent consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_grifols_dig_software_order_domain_event_OrderTaskWasCreatedEvent_total{TAG_KEY_EVENT_DISPATCHING=\"EVENT_STORE\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}